# Generated by Django 2.1.4 on 2019-01-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0002_auto_20190102_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField()),
            ],
        ),
    ]
