# Generated by Django 2.1.4 on 2019-01-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0005_auto_20190103_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstquestion',
            name='answer',
            field=models.IntegerField(),
        ),
    ]
