# Generated by Django 2.1.4 on 2019-01-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0006_auto_20190104_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstquestion',
            name='marks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='secondquestion',
            name='marks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='thirdquestion',
            name='marks',
            field=models.IntegerField(),
        ),
    ]
