# Generated by Django 2.1.4 on 2019-01-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0007_auto_20190105_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstquestion',
            name='marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='secondquestion',
            name='marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='thirdquestion',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
