# Generated by Django 2.1.4 on 2019-01-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0009_auto_20190105_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstquestion',
            name='user',
        ),
        migrations.RemoveField(
            model_name='secondquestion',
            name='user',
        ),
        migrations.RemoveField(
            model_name='thirdquestion',
            name='user',
        ),
        migrations.AddField(
            model_name='firstquestion',
            name='username',
            field=models.CharField(default='sumanth', max_length=50),
        ),
        migrations.AddField(
            model_name='secondquestion',
            name='username',
            field=models.CharField(default='sumanth', max_length=50),
        ),
        migrations.AddField(
            model_name='thirdquestion',
            name='username',
            field=models.CharField(default='sumanth', max_length=50),
        ),
    ]
